export const WEB3_LOAD_WEB3 = 'WEB3_LOAD_WEB3'

export const WEB3_GET_WEB3 = 'GET_WEB3'
export const WEB3_SET_NETWORK = 'WEB3_SET_NETWORK'
export const WEB3_SET_ACCOUNT = 'WEB3_SET_ACCOUNT'

export const WEB3_LOAD_ACCOUNTS = 'WEB3_LOAD_ACCOUNTS'
export const WEB3_LOAD_ACCOUNTS_COMPLETE = 'WEB3_LOAD_ACCOUNTS_COMPLETE'
export const WEB3_LOAD_ACCOUNTS_ERROR = 'WEB3_LOAD_ACCOUNTS_ERROR'
export const WEB3_LOAD_ACCOUNTS_NEEDS_UNLOCK = 'WEB3_LOAD_ACCOUNTS_NEEDS_UNLOCK'

export const CONTRACT_LOADING_CONTRACT = 'CONTRACT_LOADING_CONTRACT'
export const CONTRACT_LOADED = 'CONTRACT_LOADED'

export const WEB3_LOADING_COMPLETE = 'WEB3_LOADED'
export const WEB3_LOADING_ERROR = 'WEB3_LOADING_ERROR'
export const WEB3_NOT_INSTALLED = 'WEB3_NOT_INSTALLED'
export const WEB3_IS_CONNECTED = 'WEB3_IS_CONNECTED'

export const WEB3_CHECKING_NETWORK = 'WEB3_CHECKING_NETWORK'
export const WEB3_INVALID_NETWORK = 'WEB3_INVALID_NETWORK'
export const WEB3_VALID_NETWORK = 'WEB3_VALID_NETWORK'

export const CHECKING_WHITELIST = 'CHECKING_WHITELIST'

export const CONTRACTS_LOADED = 'CONTRACTS_LOADED'

export const START_SINGLE_TRANSACTION = 'START_SINGLE_TRANSACTION'
