export const WEB3_LOAD_WEB3 = 'WEB3_LOAD_WEB3'

export const WEB3_GET_WEB3 = 'GET_WEB3'
export const WEB3_GET_NETWORK = 'GET_NETWORK'
export const WEB3_GET_ACCOUNT = 'WEB3_GET_ACCOUNT'

export const WEB3_LOAD_ACCOUNTS = 'WEB3_LOAD_ACCOUNTS'
export const WEB3_LOAD_ACCOUNTS_COMPLETE = 'WEB3_LOAD_ACCOUNTS_COMPLETE'
export const WEB3_LOAD_ACCOUNTS_ERROR = 'WEB3_LOAD_ACCOUNTS_ERROR'
export const WEB3_LOAD_ACCOUNTS_NEEDS_UNLOCK = 'WEB3_LOAD_ACCOUNTS_NEEDS_UNLOCK'

export const WEB3_NETWORK_CORRECT = 'WEB3_NETWORK_CORRECT'
export const WEB3_NETWORK_INCORRECT = 'WEB3_NETWORK_INCORRECT'

export const CONTRACT_LOADING_CONTRACT = 'CONTRACT_LOADING_CONTRACT'
export const CONTRACT_LOADED = 'CONTRACT_LOADED'

export const WEB3_LOADING_COMPLETE = 'WEB3_LOADED'
export const WEB3_LOADING_ERROR = 'WEB3_LOADING_ERROR'
export const WEB3_IS_CONNECTED = 'WEB3_IS_CONNECTED'